# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='holidayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=7)),
                ('startDate', models.DateField(max_length=6)),
                ('endDate', models.DateField(max_length=6)),
                ('approved', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='htEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=7)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('mgrUID', models.CharField(max_length=7)),
                ('mgrFirstName', models.CharField(max_length=250)),
                ('mgrLastName', models.CharField(max_length=500)),
                ('holidayAllocation', models.IntegerField()),
                ('additonalHoliday', models.IntegerField()),
            ],
        ),
    ]
