# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbon', '0002_auto_20170110_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htemployee',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='htemployee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='htemployee',
            name='mgrFirstName',
        ),
        migrations.RemoveField(
            model_name='htemployee',
            name='mgrLastName',
        ),
        migrations.RemoveField(
            model_name='htemployee',
            name='mgrUID',
        ),
        migrations.AddField(
            model_name='htemployee',
            name='employeeNumber',
            field=models.IntegerField(default='111111', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htemployee',
            name='hasManager',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htemployee',
            name='managerEmployeeNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='htemployee',
            name='additonalHoliday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='htemployee',
            name='firstName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='htemployee',
            name='lastName',
            field=models.CharField(max_length=25),
        ),
    ]
